In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day48-simple-linear-regression/placement.csv")

In [3]:
data

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [4]:
X=data.iloc[:,0:1]

In [5]:
y=data.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model=LinearRegression()

In [10]:
model.fit(X_train,y_train)

LinearRegression()

In [11]:
import matplotlib.pyplot as plt

In [12]:
plt.scatter(data['cgpa'],data['package'])
plt.plot(X_train,model.predict(X_train),color='red')

In [13]:
from sklearn.metrics import mean_absolute_error

In [14]:
from sklearn.metrics import mean_squared_error

In [15]:
from sklearn.metrics import r2_score

In [16]:
y_pred=model.predict(X_test)

In [17]:
y_pred

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

In [18]:
y_test

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
23     2.48
25     3.65
6      2.60
134    2.83
165    4.08
173    2.56
45     3.58
65     3.81
48     4.09
122    2.01
178    3.63
64     2.92
9      3.51
57     1.94
78     2.21
71     3.34
128    3.34
176    3.23
131    2.01
53     2.61
Name: package, dtype: float64

In [19]:
print("MAE :",mean_absolute_error(y_test,y_pred))

MAE : 0.2884710931878175


In [20]:
print("MSE: ",mean_squared_error(y_test,y_pred))

MSE:  0.12129235313495527


In [21]:
import numpy as np

In [22]:
print('RMSE',np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 0.34827051717731616


In [23]:
print("R SCore: ",r2_score(y_test,y_pred))

R SCore:  0.780730147510384


# random feature

In [24]:
new_data1=data.copy()

In [25]:
new_data1['random_feature']=np.random.random(200)
new_data1=new_data1[['cgpa','random_feature','package']]


In [26]:
new_data1

cgpa  random_feature  package
0    6.89        0.259367     3.26
1    5.12        0.550180     1.98
2    7.82        0.215388     3.25
3    7.42        0.378322     3.67
4    6.94        0.221932     3.57
..    ...             ...      ...
195  6.93        0.040516     2.46
196  5.89        0.772179     2.57
197  7.21        0.928782     3.24
198  7.63        0.697618     3.96
199  6.22        0.925573     2.33

[200 rows x 3 columns]

In [35]:
X1=data.iloc[:,0:1]

In [28]:
y1=data.iloc[:,-1]

In [36]:
X_train1,X_test1,y_train1,y_test1=train_test_split(X1,y1,test_size=0.2,random_state=2)

In [37]:
model1=LinearRegression()

In [38]:
model1.fit(X_train1,y_train1)

LinearRegression()

In [39]:
y_pred1=model1.predict(X_test1)

In [40]:
y_pred1

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

In [41]:
print("R score",r2_score(y_test1,y_pred1))

R score 0.780730147510384


# iq

In [42]:
# new_df2 = df.copy()

# new_df2['iq'] = new_df2['package'] + (np.random.randint(-12,12,200)/10)

# new_df2 = new_df2[['cgpa','iq','package']]

In [45]:
new_data3=data.copy()
new_data3['iq']=new_data3['package']+(np.random.randint(-12,12,200)/10)
new_data3=new_data3[['cgpa','iq','package']]

In [46]:
new_data3

cgpa    iq  package
0    6.89  2.36     3.26
1    5.12  2.48     1.98
2    7.82  4.15     3.25
3    7.42  3.77     3.67
4    6.94  4.37     3.57
..    ...   ...      ...
195  6.93  2.86     2.46
196  5.89  3.37     2.57
197  7.21  4.34     3.24
198  7.63  3.36     3.96
199  6.22  1.33     2.33

[200 rows x 3 columns]

In [47]:
# X = new_df2.iloc[:,0:2]
# y = new_df2.iloc[:,-1]

In [48]:
X3=new_data3.iloc[:,0:2]

In [49]:
X3

cgpa    iq
0    6.89  2.36
1    5.12  2.48
2    7.82  4.15
3    7.42  3.77
4    6.94  4.37
..    ...   ...
195  6.93  2.86
196  5.89  3.37
197  7.21  4.34
198  7.63  3.36
199  6.22  1.33

[200 rows x 2 columns]

In [52]:
y3=new_data3.iloc[:,-1]

In [53]:
y3

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ... 
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [58]:
X_train3,X_test3,y_train3,y_test3=train_test_split(X3,y3,test_size=0.2,random_state=2)

In [59]:
model3=LinearRegression()

In [60]:
model3.fit(X_train3,y_train3)

LinearRegression()

In [61]:
y_pred3=model3.predict(X_test3)

In [62]:
y_pred3

array([4.03101751, 3.27014706, 2.51437966, 2.35012896, 1.50695108,
       1.8273873 , 2.14282766, 3.01138781, 3.97728177, 3.06511064,
       4.22634883, 3.39649805, 2.93920515, 2.51446101, 3.10485172,
       3.59530543, 1.80718944, 3.34091709, 3.06296586, 3.3726911 ,
       2.50238   , 3.30668581, 2.89955833, 3.09051874, 3.59111014,
       2.84941875, 3.3964167 , 3.52000179, 4.14029546, 2.00512781,
       3.76429119, 2.95379509, 3.66083554, 2.72294381, 2.81805149,
       3.46420261, 3.41759076, 2.69817359, 2.4170717 , 2.83173366])

In [63]:
print("R score : ",r2_score(y_test3,y_pred3))

R score :  0.8000690646519829
